Features work Youtube page
Fanger53/youtube-clone pull request #1
Opened 2020-07-10 22:50 UTC by Fanger53

this work contains a clone of youtube homepage made by 2 collaborators, the languages using in this project was HTML and CSS. the workflow you can follow it in https://github.com/BrianSammit/Youtube-page .  before the project was rejected because the repository was invalid so they couldn't review it and that was the reason to make another repository.

2020-07-10 23:48 UTC, HADDADSOHAIB requested changes
### Status: Change required :recycle: 

### Hi @Fanger53  and @BrianSammit  :hand: 

### Great job with the project, you did great work. There are some changes to be made to approve the project:
- check my comments for additional requirements.
- In the project description, there was a link that you should have used to build your project:
![image](https://user-images.githubusercontent.com/26064042/87140678-cf2f7480-c299-11ea-8a7f-90c8b7b99024.png)
http://archive.vn/Bss88
there a slight different between your project and that link in the section under the main video.

 | Source Page	| Clone Page |
|:---:|:---:|
|![Screenshot from 2020-07-10 11-51-12](https://user-images.githubusercontent.com/26064042/87147021-cd6aae80-c2a3-11ea-80bf-744427897f73.png) |![Screenshot from 2020-07-11 00-27-18](https://user-images.githubusercontent.com/26064042/87210417-5bc74a80-c30d-11ea-848e-fdf7d92dee92.png) |

- Good practice in git is to commit as much as possible and to commit atomic changes not the whole project at once, please make sure to do that from here further.
- [Optional] use the `<nav><\nav>` tag for your navbar.
- [Optional] use the `<main><\main>` tag for the main part of the HTML page.
### Once done with the changes, ask for another code review.

2020-07-10 23:48 UTC, HADDADSOHAIB commented on index.html
> +                <i class="fas fa-share"></i>
The share icon should be a button:
- [ ] It has a share button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

2020-07-10 23:48 UTC, HADDADSOHAIB commented on index.html
> +  <nav></nav>
Don't leave unused tags in your html, this is a bad practice, it clutters your code.

2020-07-10 23:48 UTC, HADDADSOHAIB commented on index.html
> +        <b><br><b><br>
This is not a correct use of `<b>` tag, we use `<b></b>` to make a text bold and it should have a closing tag. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b. Please select only the text that you want to highlight and not the whole sections of HTML code.

2020-07-10 23:48 UTC, HADDADSOHAIB commented on index.html
> +              <b><br><b><br><b><br><b><br>
- [Optional] Instead of repeating `<br>` repeatedly, use margin and padding in css files.

2020-07-13 16:24 UTC, BrianSammit commented
We made the changes from the last pull request.
we adding a margin instead of using <br> tags to make space between objects and we deleted the <nav> tag from the HTML.

2020-07-13 17:50 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Hello team 👋, great job making the changes. Really awesome project 💯 !

### However, we still need to work on some more change before we can merge.

- As requested by the previous reviewer, the section under the main video is not the same as the original page. Use this link as the source: https://archive.vn/Bss88

| Source Page	| Clone Page |
|:---:|:---:|
|![Annotation 2020-07-13 231014](https://user-images.githubusercontent.com/57726348/87335916-b0153900-c55e-11ea-9446-50c563de759e.jpg)|![Annotation 2020-07-11 155039](https://user-images.githubusercontent.com/57726348/87335932-b60b1a00-c55e-11ea-9879-543a41d9b22c.jpg)|

- The `span.slider round` is overlapping with the navbar. Please fix this.

![image](https://user-images.githubusercontent.com/57726348/87336159-0b472b80-c55f-11ea-963a-78522bd79158.png)

Apply these changes and request another review.

Happy coding 👨‍💻

2020-07-13 20:41 UTC, BrianSammit commented
we fixed the video Info part and we fixed the slider button from the recommended video.

2020-07-13 21:33 UTC, krys2fa commented
## Status: Changes Required ♻️ 

Awesome job implementing the changes requested, team 👏 
The project is really taking shape nicely. Kindly work on the following to get the project approved.

- [ ] Please include the footer section as seen in the archive. Use this link as the source: Use this link as the source: [Archive link](https://archive.vn/Bss88)

![Screen Shot 2020-07-13 at 9 22 48 PM](https://user-images.githubusercontent.com/18187039/87354968-0ed2b680-c54f-11ea-8bc5-76093468490c.png)


- [ ] [OPTIONAL] The use of semantic HTML tags like `<main>` and [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) are highly encouraged.

- [ ] [OPTIONAL] Please update the link to the live version of your project in the README.md file to ensure that the latest updates to your project can be easily seen.

Apply these changes and request another code review. 
Feel free to reach out for any clarification or assistance.

Happy Coding 🖥️  😃 
@ Chris Amanor [slack]

2020-07-14 14:33 UTC, Fanger53 commented
adding footer and update live demo from Readme

2020-07-14 16:31 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

While applying changes to the footer, you have introduced a horizontal scrollbar 👇 

![image](https://user-images.githubusercontent.com/57726348/87450899-c71a6080-c61c-11ea-8615-b83d5a99d5c1.png)

I see that you have set the width of the footer as 100vw and also margins on all sides. Remember the box-model here. Margins are not part of the content. So right now, your footer's width is 100vw+(25px+25px), which is greater than any screen width. That's why the overflow. 


Your project looks absolutely fantastic. Just make this change and apply for another code review.

Happy coding 👨‍💻

2020-07-14 16:45 UTC, BrianSammit commented
we change the width footer.

2020-07-14 17:02 UTC, krys2fa commented
# Status: Project Approved! 🏁 
Congratulations on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

2020-07-14 17:07 UTC, merged